server:
    port: 9001

# spring:
#   application:
#     name: DEPARTMENT-SERVICE
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296 # config-server port:9296

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
#     service-url:
#       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#   instance:
#     hostName: localhostsrc/main/resources/application.properties